In [1]:
import numpy as np

In [3]:
ones = np.ones((2, 4), dtype='int')
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [5]:
zeros = np.zeros((4, 2), dtype='int')
zeros

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [6]:
# Not inclusive
arng = np.arange(1, 11, 1)
arng

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
lspc = np.linspace(0, 100, 11)
print(lspc)
lspc_1 = np.linspace(1, 100, 10)
print(lspc_1)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [13]:
trs = np.array([range(5), range(5), range(5)])
print(trs)
reshaped = trs.reshape(3, 5)
print(reshaped

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [14]:
rshp = np.array([range(12)]).reshape(2, 6)
rshp

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])